<?php

/**
 * @file
 * Creates a GitHub web hook endpoint.
 */

/**
 * Implements hook_menu().
 */
function fbleads_webhook_menu() {
  $items = array();

  $webhook_url = variable_get('fbleads_webhook_url', 'fbleads/webhook/%fbleads_webhook_token');
  $items[$webhook_url] = array(
    'title' => 'FBleads WebHook Endpoint',
    'page callback' => 'fbleads_webhook_endpoint',
		//'page arguments' => json_decode(file_get_contents('php://input'), true),
    'access callback' => TRUE,
    'type' => MENU_CALLBACK,
    'file' => 'fbleads_webhook.pages.inc',
    'delivery callback' => 'fbleads_webhook_json_deliver',
  );

  // Add dynamic arguments to page and access callbacks.
  $arguments = array();
  $url_parts = explode('/', $webhook_url);
  foreach ($url_parts as $position => $part) {
    if (0 === strpos($part, '%')) {
      $arguments[] = $position;
    }
  }

  $items[$webhook_url]['access arguments'] = $arguments;
  $items[$webhook_url]['page arguments'] = $arguments;

  $items['admin/config/services/fbleads-webhook'] = array(
    'title' => 'fbleads WebHook',
    'description' => 'Configure the fbleads WebHook that responds to events.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('fbleads_webhook_settings'),
    'access arguments' => array('administer site configuration'),
    'file' => 'fbleads_webhook.admin.inc',
  );

  return $items;
}

/**
 * Implements hook_entity_info().
 */
function fbleads_webhook_entity_info() {

  $info = array();

  $info['fblead'] = array(
    'label' => t('Facebook lead'),
    'base table' => 'fbleads_webhook_leads',
    'entity keys' => array(
      'id' => 'id',
      'label' => 'name',
    ),
		'entity class' => 'Entity',
		'controller class' => 'EntityAPIController',		
    'module' => 'fbleads_webhook',
  );

  return $info;
}
